### ISSUE TITLE
two questions on feature assignment/identification

### ISSUE THREAD

**Issue by kim17753** [mzmine/mzmine#1199]
### Basic information

* My operating system and version: Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz   3.00 GHz (RAM 64 GB)
* My MZmine version: MZmine 2.5.3

### What happened

Hi! I love MZmine! Just started playing with since last week and after reading and watching many provided resources (manuals, tutorials etc.), I was able to eventually come to the feature assignment/identification steps.

**Q1. Is there a way to select several local ms databases to allow the MZmine for feature assignment?** 
I currently have Metline databases with lipids, metabolomics, petites etc. and will like to use all of these database to identify the compound based on their mass and isotopic pattern. Is there a way to select all of them at once?

**Q2. Does the compound identification from library serach overwrites on predicted formula?** 
I first tried formula prediction. Then I tried online base library search (KEGG) but didn't give me any identified compound. Could this be caused by the initial predicted formula being assigned already? Then if I used other libraries for identification, will it not overwrite the identified compound on the predicted formula?

I do have many questions but will stop here first. I would greatly appreciate your advice! Thank you!

**Comment by robinschmid** [comment]
You mean METLIN? 
So there is spectral library matching and CSV compound annotation - which just matches m/z, RT , etc. Its gonna be even easier in the next upcoming release. Soon.

The online search is not maintained and we deactivate it in the next release. Its better to use spectral libraries (look into the documentation) and SIRIUS and GNPS for annotation. 

You can use the new wizard once we release MZmine 3.4
