### ISSUE TITLE
Multivariate curve resolution Preview is missing since 3.4.0

### ISSUE THREAD

**Issue by nic-Oban** [mzmine/mzmine#1377]
### Basic information

* My operating system and version: windows 10 64b
* My MZmine version: from 3.3.19 to 3.5.4

### What happened

* Please describe what happened and how it differs from what you expected to happen: the module multivariate curve resolution (Spectral deconvolution (GC)) doesn't show the preview since 3.4.0. Everything was ok with 3.3.19 (and maybe some further development versions in the 3.3.x branch I didn't test).

* Please upload screenshots of any errors **and** your log/mzmine.log file.
Module in 3.5.0 :
![3 5 0](https://github.com/mzmine/mzmine3/assets/32569756/65597ace-ebeb-494a-b740-a17fcbc5bba3)
Same module in 3.3.19 :
![3 3 19](https://github.com/mzmine/mzmine3/assets/32569756/21b27854-c2b3-4db1-b245-591ebfa12319)

* Issues opened without an example project are unlikely to be processed: the GUI issue can be reproduced without opening any file.

As this module is nearly impossible to use without any preview, is it planned to restore the preview option in the GUI please? If I can help with any information, please, do ask!
Have a beautiful day!

**Comment by tomas-pluskal** [comment]
@asmirn1 @du-lab Could you please check this?

**Comment by tomas-pluskal** [comment]
@tnguy271 @asmirn1 @du-lab Could you please check this?

**Comment by nic-Oban** [comment]
Hello @tomas-pluskal @tnguy271 @du-lab @asmirn1 @SteffenHeu 
is there any chance to get the ADAP modules back in the v4 new versions?
I tried the new GC-EI-MS wizard modules but I find the GC-EI spectral deconvolution less easy to tune and eventually less accurate.
Thanks a lot and congrats for this new version! It's beautiful.

**Comment by ansgarkorf** [comment]
Hi,
thanks for the kind feedback. We temporarily deactivated some ADAP GC modules. Plan is to reactivate them in the near future. Can you show us a comparison of an accurate deconvolution result with ADAP with MZmine 3 vs a less accurate one with the new GC-ES deconvolution in mzmine v4?
If you have any input or suggestions on how to accurately perform GC-EI spectral deconvolution we are always happy for feedback.
kind regards,
Ansgar

**Comment by ansgarkorf** [comment]
Great, thanks for coming back to this issues.
