### ISSUE TITLE
manually integrate a scan-range of a Chromatorgam to export a HRMS-spectrum

### ISSUE THREAD

**Issue by SimonRedl** [mzmine/mzmine#1585]
Hi MZmine-community,
I hope this question was not asked before and I repeat the question. I couldn't could find my issue on the internet. I apologize if I overlooked something and waste your time. My goal is it to find an open-source program that can manually integrate the high-resolution sprectra of multiple scans (or retention time window) of one chromatogram manually or the whole chromatogram that does not require high programming skills. For now I work with Xcalibur and Freestyle from Thermo Fisher (Orbitrap) to do that. There you can just set a scan range or select your scans manually and then export the integrated spectra as .raw data that I then convert to mzML. Is that kind of work possible in MZmine. I tried to find a way with OpenMS and Openchrom but could not find a solution for my problem.
Hopefully someone can help me.
Best regards
Simon Redlich

**Comment by SteffenHeu** [comment]
I'm not really sure what you mean. If you want the area of your chromatographic peaks you can do that with MZmine. 
You should note that MZmine is designed for untargeted analysis. Sou you will get a table of all signals, not jsut specific m/zs.

You can start with the wizard: https://mzmine.github.io/mzmine_documentation/wizard.html and use the the "Local csv datatabse" in the "annotation" tab. An example csv can be found here: https://mzmine.github.io/mzmine_documentation/module_docs/id_prec_local_cmpd_db/local-cmpd-db-search.html

**Comment by SimonRedl** [comment]
@SteffenHeu Many thanks for your fast answer. Maybe I give you a bit more information about my project: I don’t have any peaks in my chromatogram because I have a direct injection of my water sample (DOM-analysis) into my Orbitrap without any column in between and therefor more like a broad plateau. My whole "chromatogram" consists of 258 Scans over 5 min of my constantly injected sample. Out of these 258 scans containing a HR-massspectra each I want 100 scans to be combined into one spectra (average). For now I use Xcalibur for that by selecting the scan range (100 scans approx. RT = 1-3 min) manually generating an single integrated spectra, that I then export as a new .raw datafile. This new raw-datafile consists of one scan but of course lost all information of the “chromatogram”. As chance would have it, I met Tomáš Pluskal during a talk in Jena and asked him about my problem yesterday. I took the opportunity to ask him about my issue and listen to his excellent talk. He told me that he does not believe that Mzmine 3 can do that as easy and convenient as the Xcalibur software from Science Fisher but he sad i should try to ask you to get that clarified. He sad it could be possible that the "chromatogram builder" could identify my whole scan area, if i use the right set of parameter. I tried it but could not make it happen. Does anyone else know how i could achieve my goal?

**Comment by ansgarkorf** [comment]
Hi Simon,
what is your plan with the new merged spectrum of 100 scans? 
Have you checked out the flow injection option of the wizard? 
![image](https://github.com/mzmine/mzmine3/assets/27132602/57241a80-70a9-493b-844b-abee0c4f9db3)

kind regards,
Ansgar

**Comment by SimonRedl** [comment]
Thanks Ansgar, for the fast response. No not entirely, but will do that now. Maybe I find something useful.

I want to export a new mzml with the combined averaged spectrum of the 100 scans of all my samples and feed it to OpenMS. There I found a workflow to compare all the features of my samples and combine to one csv-Data that I then can upload to UME (Ultra Mass Explorer) for my DOM-Analysis.

Kind regards
Simon Redlich
