### ISSUE TITLE
Hmdb spectral library search not running

### ISSUE THREAD

**Issue by ChauTran112** [mzmine/mzmine#1598]
### Basic information

* My operating system and version: Win 10
* My MZmine version: 3.9.0

### What happened

When I imported the hmdb spectral library into MZmine, it loaded to MZmine. However when I performed spectral identification, no features was match with the spectral library and it only took MZmine around 1 second to run the file which is very strange because it normally take a lot more time. I set m/z tolerance very high 0.1 m/z and 40 ppm so if I understand correctly, it should fine some match whether it's correct or not, I also set the parameters lower but the results still the same. While I only have MS1 data, I believe I still should receive some matches. My sample is human serum sample and I use MoNA hmdb. jason library. 
![image](https://github.com/mzmine/mzmine3/assets/153539490/276ad3db-ad1d-49fd-98b1-109bb4cdbeb0)
Spectral library
https://drive.google.com/file/d/12a_gJ28RGqs6HndDlSHSdnrzdEqTfVy8/view?usp=sharing
MZmine data (the feature list that I use for annotation is join aligner peak finder)
https://drive.google.com/file/d/1Ux2ca5VMLBDiyzR6AtoBpP4RGWw5mxmC/view?usp=sharing

**Comment by ChauTran112** [comment]
Hi, 

I took the database from:
https://gnps-external.ucsd.edu/gnpslibrary
https://mona.fiehnlab.ucdavis.edu/downloads
I used HMDB database and I tried a few types of file formats (mgf and json) but none of them worked.

I'm not sure if this is the database problem or is my setting in MZmine couldn't match to the library.

Thank you so much!
Chau.

**Comment by SteffenHeu** [comment]
Sorry for the late reply. If the library does not contian the necessary information in the proper fields, we cant do anyhting about it.
