### ISSUE TITLE
Feature list import

### ISSUE THREAD

**Issue by froz9** [mzmine/mzmine#1662]
### Basic information

* My operating system and version: Windows 11
* My MZmine version: 3.9.0

Hello,

I am interested in testing some recently published alignment algorithms (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-023-05525-4#Sec2). According to the documentation, there should be an option to import these algorithms (https://mzmine.github.io/mzmine_documentation/module_docs/io/feat-list-import.html). However, I am unable to locate this function in the software.

Could someone please assist me in finding this feature? Any help would be greatly appreciated.

Thank you in advance.

**Comment by SteffenHeu** [comment]
Import of feature lists is not supported anymore. sorry for the inconvenience.
