### ISSUE TITLE
Windows 10 22H2 compatibility

### ISSUE THREAD

**Issue by QuentinD16** [mzmine/mzmine#1711]
### Basic information

* My operating system and version: Windows 10 enterprise
* My MZmine version: 3.3.0

### What happened
Hello,

We plan to migrate to Windows 10 22H2 and I wanted to know if my version of MZmine will still be supported?
thanks in advance,
best regards,
Quentin.

**Comment by ansgarkorf** [comment]
Hi,
yes, and I recommend to upgrade to 3.9.0
kind regards,
Ansgar
