### ISSUE TITLE
Cannot open raw files in Windows10 (error java.lang.Exception: No scans found (ThermoRawImportTask.java:189)

### ISSUE THREAD

**Issue by cHRefthym** [mzmine/mzmine#1717]
### Basic information

* My operating system and version: Windows10 Pro
* My MZmine version: 3.9.0

### What happened
I have Thermo raw files (LC-MS) that I'm trying to open but the import fails with the following error:

java.lang.Exception: No scans found (ThermoRawImportTask.java:189)

I added the log file for checking. Thank you
[mzmine_0_0.log](https://github.com/mzmine/mzmine3/files/14551863/mzmine_0_0.log)

**Comment by SteffenHeu** [comment]
search for the "mzmine_thermo_raw_parser" folder in the mzmine temp folder and the system temp folder and delete it.

**Comment by RCHdeVos** [comment]
same problem as cHRefthym, also after completely cleaning the mzmine temp folder
