### ISSUE TITLE
Mixed up eps and emf export of graphs

### ISSUE THREAD

**Issue by JSchmeinck** [mzmine/mzmine#1801]
### Basic information

* My operating system and version: Windows 10 Education 19045.4291
* My mzmine version: 3.9.5

### What happened

I opened the TIC visualizer tab of a feature by using right click on the shape of the feature in the feature list and clicking Show... -> XIC (quick). While trying to export the graph using right click on the graph and then Export As i noticed that the options for the eps and emf export are mixed up. That means that clicking on eps leads to the export of an emf file and vice versa. I have noticed this for all other instances where graphs can be exported.

**Comment by robinschmid** [comment]
Interesting. I think we removed some of the options for the new release as they were buggy at times and pdf should suffice.
