### ISSUE TITLE
NIST MS Search for GC-EI-MS

### ISSUE THREAD

**Issue by woshibaipiaogua** [mzmine/mzmine#1821]
### Basic information

* My operating system and version:win11
* My mzmine version: 4.0.8

### What happened

When annotating with NIST MS Search, there are significant issues with the annotation results. The min cosine similarity function seems to be malfunctioning, as all matched substance results display a min cosine similarity of 0.999, which is clearly impossible.
![annotating with NIST MS Search](https://github.com/mzmine/mzmine3/assets/105028723/c6aa378a-9b1d-40be-b75a-dbbf2f1b1cf6)

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the mzmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by zglong1** [comment]
Following up on this, when I try the search, it seems like only the highest MW peak is being searched against the database, instead of the full spectrum. 
<img width="838" alt="example" src="https://github.com/mzmine/mzmine3/assets/121990792/25d1b186-e155-4c7e-8ceb-f4e0f33c5860">

**Comment by pgisurender** [comment]
Dear Developers 
I am facing exactly same issue with NIST search.
My MZmine is exporting GC-GNPS-MS file but of  0 KB.

Regards
Surender
![NIST match](https://github.com/mzmine/mzmine/assets/167277849/35440c86-3aa3-4bbc-8654-e5c258617a06)

**Comment by robinschmid** [comment]
This module is quite old and unmaintained. But we are in contact with NIST and are discussing how to best integrate their libraries in MZmine. 
I guess that all posters here are working on GC-EI-MS data?
The module might only support MS2 at the moment. But we will work on the GC-EI-MS part.

**Comment by zglong1** [comment]
That's correct, at least for me - GC-EI-MS data

**Comment by dav7841** [comment]
I'd like to add here that I'm experiencing the same with mzmine version 4.0.8. but not on v3.9.0. Using the same data and similar work flows (ADAP builder, resolver, devonvolution) on v3.9.0 will return proper NIST results. The entire spectrum is exported to NIST for searching, where in 4.0.8 only the main feature ion is exported.

**Comment by ansgarkorf** [comment]
Please update to 4.1, released yesterday. A fix was introduced. Let us know if it works.

**Comment by dav7841** [comment]
This has worked, exporting the full spectrums now to NIST on 4.1. Many thanks!

**Comment by ansgarkorf** [comment]
Perfect, thanks for the fast feedback!
