### ISSUE TITLE
Value selection in ListWithSubsType in TableView is broken

### ISSUE THREAD

**Issue by robinschmid** [mzmine/mzmine#1823]
Somehow the cells or cellvalue factory of ListWithSubsType in TableViewFX is broken. The values are shown as a list sometimes and sometimes as first element in list. This is true for multiple ListWithSubsType like ion identity or online reaction. 

Maybe its the cell value factory or the cell factory. The compobox works and selecting a value seems to update too many other cells as well... they seem to be linked so maybe something wrong with the cell facotry

![image](https://github.com/mzmine/mzmine3/assets/10366914/73efc45a-af77-4913-b999-39f6c61c40a7)

**Comment by SteffenHeu** [comment]
should be fixed in #1843
