### ISSUE TITLE
Chromatogram resolving - local minimum resolver - issue 

### ISSUE THREAD

**Issue by ana-kovacic** [mzmine/mzmine#1857]
### Basic information

* My operating system: windows 10, enterprise 2016
![image](https://github.com/mzmine/mzmine/assets/128139739/bc661969-c604-4738-831d-a003e50bef85)

* My mzmine version: mzmine 4.0.12 (prior 4.0.8)

### What happened
One week ago, I was able, after mass detection and adap chromatogram bulding, set the parameters also for the next step --> chromatogram resovling, using local minimum resolver. This week I am trying similar things with slight difference in noise level and min. peak intensity, and when selecting chromatogram resovling --> local minimum resolve, the mass fetaures resolved are created automatically, not allowing to set the resolving paramters, and I am noticing that I  lossing relevant mass features. Do you maybe know what is the reson and if there is different way for setting the resovling paramters?  

Please find attached three examples of my samples and also the data processing workflow of my data set with selected parameters. 
Please let me know, if you need anything else. 
Thank you.
Ana 
https://drive.google.com/file/d/1FJRidj9dcabP696JpJQMuedj-n51wmnq/view?usp=sharing, https://drive.google.com/file/d/1rmTTcafmmjrqfgyRbDSvQdn9yWIiZkwc/view?usp=sharing, https://drive.google.com/file/d/1tj9KfJ20lp40yayOEh3CCQ3Cf8Dy8qVP/view?usp=sharing

[Data processing_workflow_issue.docx](https://github.com/mzmine/mzmine/files/15335160/Data.processing_workflow_issue.docx)

**Comment by robinschmid** [comment]
So you mean that the dialog does not open and it directly runs the step instead?
I have noticed this once now and I am not sure why. 
For me restarting mzmine resolved the issue and it was gone for now. 
Otherwise we recommend using the mzwizard to generate a batch mode and run the batch mode. You can still optimize your parameters there. 

Best 
Robin

**Comment by ana-kovacic** [comment]
Hi Robin,

Yes, I have done it like you have suggested, and installed the older
version which was working, mzmine 4.0.8, and it was again working fine,
while I was not able to find anymore the version 4.0.12, which should be
the latest but which was also not working.

However, now it seems that the latest version is 4.0.8, which is also
working fine.
Thank you.
best,
Ana

**Comment by robinschmid** [comment]
4.0.12 was only a nighly build so a test version. We will publish 4.1.0 soon. So please try this one as soon as it will be available and get back to us if there are any issues.

**Comment by ana-kovacic** [comment]
Will be my pleasure to try it, also good job on the new versions!
Processing more than 600 data files, full scan, without big problems and
much much faster than previous.
Best,
Ana

**Comment by ansgarkorf** [comment]
Hi Ana,
have you already upgraded to 4.1? Can you confirm the issue was solved?
kind regards,
Ansgar

**Comment by ana-kovacic** [comment]
Hi Ansagar,

I am confirming that the issue is solved with the upgraded version.
At this point may I also ask you if it is possible to enable the academia
account through my two research institutions, since I was able to get
only the trial one so far, and this step seems to be working only with an
active account.
Research institution:
Fondazione Edmund Mach, San Michele all'adige, Trento, Italy, and
Jožef Stefan Institute, Ljubljana, Slovenia

Thank you.
Best,
Ana

**Comment by ansgarkorf** [comment]
Hi Ana,
glade to hear the problem was solved. Please send an e-mail to info@mzio.io with info on your user account so we can solve the registration issue.
kind regards,
Ansgar

**Comment by ana-kovacic** [comment]
Great, thank you.
Best regards,
Ana
