### ISSUE TITLE
Registering to the new Mzmine version

### ISSUE THREAD

**Issue by nesrinehegazi** [mzmine/mzmine#1868]
I registered for the new mzmine version 4.0.8 as an academic user using my institutional email, yet it is was set up as a commercial account with a 30 day trial version>

How can I fix this issue, please???
### Basic information

* My operating system and version: windows 10
* My mzmine version:  4.0.8

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the mzmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by ansgarkorf** [comment]
Hi,
please send an e-mail to info@mzio.io including your user information.

**Comment by nesrinehegazi** [comment]
Thanks alot
