### ISSUE TITLE
Registeration problem with Mzmine 4.0.8

### ISSUE THREAD

**Issue by nesrinehegazi** [mzmine/mzmine#1879]
I registered with my institutional email yet I got a commercial account with a 30-day free trial.
I emailed my user info to info@mzio@io a couple of days ago and received no reply.
Would you please help me resolve this issue? My institutional email is nm.hegazi@nrc.sci.eg

* My operating system and version: win10
* My mzmine version: 4.0.8

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the mzmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by robinschmid** [comment]
My colleague checked. Somehow info@mzio.io did not receive any email. 
Can you try again to send one?

Also your institution was added to the list of academic non-profit institutions. Just login again in mzmine.

Best regards   
RObin

**Comment by nesrinehegazi** [comment]
> My colleague checked. Somehow [info@mzio.io](mailto:info@mzio.io) did not receive any email. Can you try again to send one?
> 
> Also your institution was added to the list of academic non-profit institutions. Just login again in mzmine.
> 
> Best regards RObin

Thanks a lot. Much appreciated.
I have sent an email again in reply to your email. Hopefully, you will receive it.
Sometimes there are technical issues with the email and it gets delayed.
