### ISSUE TITLE
The startMZmine_Linux.sh file is not found. How to start mzmine4 in Linux system?

### ISSUE THREAD

**Issue by jeep3** [mzmine/mzmine#1880]
### Basic information

* My operating system and version: CentOS 7
* My mzmine version: mzmine-4.0.8

### What happened
I want to ask a simple question. In the Linux system, after downloading the installation file(mzmine_Linux_portable-4.0.8.zip ), the startup file is not found after decompression, such as the startMZmine_Linux.sh file (sh startMZmine_Linux.sh or ./ startMZmine_Linux.sh to start). Has anyone encountered the same problem?
* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the mzmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by jeckel24** [comment]
Yes, have you solved this? If so, can you share how?

**Comment by robinschmid** [comment]
The startup script was from mzmine 2. 
Since then we are shipping the Java Runtime with mzmine and you can just directly run mzmine.
