### ISSUE TITLE
Display compatibilities

### ISSUE THREAD

**Issue by oolonek** [mzmine/mzmine#1894]
**Is your feature request related to a problem? Please describe.**

I might have overlooked it but couldn't find the list of supported platform for the latest mzmine release (https://github.com/mzmine/mzmine/releases/tag/v4.1.0)
In my case a macbook pro from 2019 
`machdep.cpu.brand_string: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz`

The latest version v4.1.0 appears to be unsupported :(

I can open v4.8.0 even though the installer display a red cross and a crossed logo.

![image](https://github.com/mzmine/mzmine/assets/2760049/0af7a3ab-c97d-45fe-8a04-a398f6b7b73e)

**Describe the solution you'd like**
A better description of the supported architectures.

**Comment by oolonek** [comment]
Any news on this issue ?

**Comment by kyrasolaris01** [comment]
Hi,
We don't have a build pipeline for intel based Macs anymore, because GitHub stopped the support. You can stick to previous versions or download the source code and compile the software locally. In the documentation you find a developer tutorial to do that.
Kind regards
Ansgar

**Comment by ansgarkorf** [comment]
Hi,
We don't have a build pipeline for intel based Macs anymore, because GitHub stopped the support. You can stick to previous versions or download the source code and compile the software locally. In the documentation you find a developer tutorial to do that.
Kind regards
Ansgar
