### ISSUE TITLE
GC-Aligned Feature List - Alignment columns

### ISSUE THREAD

**Issue by kriskiland** [mzmine/mzmine#1895]
### Basic information

* My operating system and version: Windows 10 Pro. 21H2.
* My mzmine version: 4.1.0

### What happened

Hi there,
After using GC Aligner, my aligned feature list does not display the alignment columns, such as Rate, Number of Aligned Features, etc. When I use the dropdown menu on the right (the + symbol), there are no checkboxes for any alignment columns. Hitting "Toggle alignment columns" does nothing either.

![image](https://github.com/mzmine/mzmine/assets/168223573/36cf1882-9411-4a9d-8e8a-3eeb84c25038)

In the table options, I am able to select alignment columns but they still do not display in the table (see below).

![image](https://github.com/mzmine/mzmine/assets/168223573/1170c774-d55e-49e3-aa76-c24e8f0f1481)

--------

![image](https://github.com/mzmine/mzmine/assets/168223573/699816ab-c273-4c49-b15a-debad1522f91)

--------

On the other hand, when I use the Join Aligner, I can get all of the alignment columns in my feature list, so this seems like it's a problem specific to the GC aligner.

![image](https://github.com/mzmine/mzmine/assets/168223573/2abadd59-75eb-4e2e-bbc4-6e55a28e8196)

Thanks for the help,
Kris

**Comment by ansgarkorf** [comment]
Hi,
truth is there is currently no alignment score implemented for GC. Feel free to come up with a proposal.
https://github.com/mzmine/mzmine/blob/4a358d9d83c94dcf2013039f7d439130ceab9282/mzmine-community/src/main/java/io/github/mzmine/modules/dataprocessing/align_gc/GcRowAlignScorer.java#L51

**Comment by ansgarkorf** [comment]
Alignment scores are now added for GC-MS, please test the latest development build
