### ISSUE TITLE
Problem with saving the project with the new mzmine

### ISSUE THREAD

**Issue by carobirer** [mzmine/mzmine#1897]
### Basic information

* My operating system and version:  Windows 10 Éducation 64bit
* My mzmine version: 4.0.8

java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)

![mzmine_error_save](https://github.com/mzmine/mzmine/assets/38260122/c78dde20-cc31-4f29-ba56-68344402f60a)
![mzmine_error_save](https://github.com/mzmine/mzmine/assets/38260122/3940c952-98a4-48c7-906c-37bc8fa3ca7f)

### What happened
Hi, 
I am having trouble to save modifications on my mzmine project since the new mzmine. Those are mzmine project I have made with a previous mzmine version. See in the screenshot the error message, has something to do with Java ?
Thank you for your help

**Comment by SteffenHeu** [comment]
Hi,

please upload the batch file that you used to create the project, so we can reproduce the error, otherwise there is little we can do. Otherwise upload the log file.

**Comment by carobirer** [comment]
[mzmine_0_0_log_file.txt](https://github.com/user-attachments/files/15886902/mzmine_0_0_log_file.txt)
Hi, 
Thanks for your help. Here is the log file, I don't have any batch file. I have updated mzmine to the last version 4.10 and it doesn't fixed the problem.
Thanks
Caroline

**Comment by ansgarkorf** [comment]
Hi,
I looked into your log file. The problem is you used a module when creating the project with mzmine 3 that is currently not supported in mzmine 4, namely ADAP resolver. Try to reprocess everything with the local minimum resolver and make sure to delete all features lists that were created with the ADAP resolver. Than you should be able to save the project.

**Comment by carobirer** [comment]
Thank you Ansgarkorf, this makes sense. I also had other issues with MZMINE4.1 like exporting files to GNPS or SIRIUS which was not working even with a new project started only under 4.1 with no ADAP, so I have decided to remove 4.1 and re install 3.9 for now. Thanks again for your help,

**Comment by ansgarkorf** [comment]
Hi,
that is really unfortunate. Please also have a look at this issue where people have a similar problem with the export: https://github.com/mzmine/mzmine/issues/1690
