### ISSUE TITLE
Cannot load module class (BaseLine Correction)

### ISSUE THREAD

**Issue by jbcoffin** [mzmine/mzmine#1901]
### Basic information

* My operating system and version: Windows 11 v. 23H2 (build 22631.3593)
* My mzmine version: 4.0.8

### What happened
* I wanted to start a Baseline correction of my netCDF data and received this message : 
"Cannot load module class io.github.mzmine.modules.dataprocessing.filter_baselinecorrection.BaselineCorrectionModule"
(GUI path to module : Raw data methods>Raw data filtering>Baseline correction)
And, indeed, i couldn't find this module in the git repository.

**Comment by SteffenHeu** [comment]
Hi, thanks for reaching out. Indeed we did remove the baseline correction module, because noone of the current developers was maintaining it. Apparently we forgot to remove it from the main menu. A replacement will be added in the future.
