### ISSUE TITLE
Error when building mzmine from source in Linux HPC

### ISSUE THREAD

**Issue by WBS-TW** [mzmine/mzmine#1902]
### Basic information

* My operating system and version: Rocky Linux 9.4
* My mzmine version:  4.1.0

### What happened

We are trying to do a local installation of mzmine in a HPC from the source code using the instructions to use gradle. successful build with the ./gradlew command, we cannot find the "build/jpackage" folder.
The HPC has Gradle 9.0 and we got some warning messages that deprecated gradle features were used with this build, making it incompatbile with gradle 9.0. Dont know if this would be the issue?

**Comment by robinschmid** [comment]
Hi Thanks for reaching out. 
Why are you using gradle 9? Latest version is 8.8
https://gradle.org/releases/

Why not just pull the version from out releases:
https://github.com/mzmine/mzmine/releases/latest

**Comment by WBS-TW** [comment]
Thanks Robin,
It was a recommendation by our IT support to build from source  but now we can pull and run the portable Linux version. 
Thanks for the help!
