### ISSUE TITLE
Unhandled exception for ADAP chromatogram builder step

### ISSUE THREAD

**Issue by Isabelle802** [mzmine/mzmine#1921]
### Basic information

* My operating system and version: windows 10 Pro 64 bits
* My mzmine version: 3.9.0

### What happened

I work with Thermo Raw Data (from Exploris 120). I did both mass detection steps (MS level 1 and MS level 2).
When I want to do the ADAP chromatogram builder step, I have the following error message:
Unhandled exception in task directory chromatograms in 231123035.raw: java.lang.NullPointerException (Reference Pipeline java:214)

Please find the capture of the error message and the log file.
[230619_mzmine_0_0.log](https://github.com/user-attachments/files/15899379/230619_mzmine_0_0.log)
![240619_error](https://github.com/mzmine/mzmine/assets/173256575/1bae5245-cce1-4cf8-a8e5-e0796efee11b)

You can upload the standalone project using the following link:
https://ent.normandie-univ.fr/filex/get?k=76t7VUywNiMuwJFsIz2

Many thanks for your help.
Isabelle

**Comment by ansgarkorf** [comment]
Hi,
I tested your project with mzmine 4.1. I build a batch with the mzwizard and got good results. Please update to the latest version.
kind regards,
Ansgar
![image](https://github.com/mzmine/mzmine/assets/27132602/bea064a3-812d-4049-84dc-d09030a2b67d)

**Comment by SteffenHeu** [comment]
![grafik](https://github.com/mzmine/mzmine/assets/37407705/a7897444-e7e9-49d6-b322-1b3097516ac0)

The issue is that the mass detection was applied from 0-20 min, but probably no RT filter was used for the chromatogram builder. therefore some scans do not have a mass list and then the chromatogram builder fails.

**Comment by Isabelle802** [comment]
Many thanks for all advices and so quick answer! I forgot to put the RT filter for the ADAP chromatogram builder and it's working also with the 3.9.0 version.
