### ISSUE TITLE
MZmine 4.1.0 not compatible with Intel Core Mac with OS 14.5?

### ISSUE THREAD

**Issue by bsedio** [mzmine/mzmine#1934]
### Basic information

* My operating system and version:
* Processor: 2.4 GHz 8-Core Intel Core i9
* Graphics: Intel UHD Graphics 630 1536 MB
* Memory: 64 GB 2667 MHz DDR4
* MacOS 14.5 (23F79) Sonoma
* My mzmine version: 4.1.0

### What happened

I downloaded mzmine_macOS_installer-4.1.0-academia.dmg but when I try to install it, I receive this message: "You can’t open the application “mzmine” because this application is not supported on this Mac." I get the same message when attempting to use the .zip version.

I was able to install and run MZmine version 4.0.8

Thanks again for all of your amazing work!

**Comment by SteffenHeu** [comment]
Hi bsedio,

apparently github moved the macOS action from x86 to arm, making new releases only compatible with arm chips. A x86 action is only available to paying repositories, which is not feasible at the moment. You can either use mzmine 4.0.8 or compile mzmine yourself. Basically follow this guide: https://mzmine.github.io/mzmine_documentation/contribute_intellij.html
