### ISSUE TITLE
Error importing .raw data files in window 10

### ISSUE THREAD

**Issue by sammywinchester19** [mzmine/mzmine#1945]
### Basic information

System windows 10 enterprise
Mzmine 4.1.0

Hi, I am having troubles importing raw data files into mzmine 4. My error in the log file says

2024-07-03 11:26:07 SEVERE io.github.mzmine.modules.io.import_rawdata_all.AllSpectralDataImportModule runModule Could not identify the data type needed for import of n files=1. The file/path might not exist.

I installed Mono on my system according to one recommendation from a previous thread but still the .raw files cannot be imported.

![Mzmine error](https://github.com/mzmine/mzmine/assets/67588791/0ea2de08-44c0-49af-b94c-359136b6b81c)

**Comment by SteffenHeu** [comment]
Mono is an app for linux and mac, not for windows, so there seems to be another issue.

What kind of file are you importing?

**Comment by sammywinchester19** [comment]
The file format is Waters Aquity G2 Q-TOF .raw file

**Comment by ansgarkorf** [comment]
The .raw import is for Thermo data. For Waters please read this:
https://mzmine.github.io/mzmine_documentation/data_conversion.html#waters
