### ISSUE TITLE
Unable to convert Waters cyclic IMS data to open source

### ISSUE THREAD

**Issue by Valerie-Maes** [mzmine/mzmine#1951]
I cannot convert my LC-MS/MS data from a Waters cyclic IMS instrument to open source to upload it in MZmine. 
I tried the Waters Data Connect software and they don't support ion mobility.

Is there another way to convert the data and make it compatible with MZmine?

Thanks!

**Comment by ansgarkorf** [comment]
Hi, that is unfortunate. Have you contacted Waters what they recommend for IMS data conversion?

**Comment by Valerie-Maes** [comment]
Hi, yes. 
The software support contact person told me they cannot convert it at the moment. They are going to integrate it in the conversion tool somewhere in the future but they will only start looking into it at the end of this year. 
So I wondered if anyone else had a solution.

**Comment by ansgarkorf** [comment]
Okay, thanks for the input. Sadly, I am currently not aware of any other tool that can do the conversion.

**Comment by SteffenHeu** [comment]
You can alwas try your luck with MSconvert, but we have to warn you that we have had varying results with that in the past. Try to recalibrate the file in mass lynx and maybe move the lockmass function out of the folder after calibration but before conversion. 

We cannot guarantee that this will work as you would expect.
