### ISSUE TITLE
User account

### ISSUE THREAD

**Issue by dav7841** [mzmine/mzmine#1968]
Hi, 
Sorry if it's inappropriate to post here about this. I've attempted to contact through the mzmine website but I haven't heard a reply yet. I attempted to create a user account as an academic user but it setup as a trial user. Now my trial has expired and I'm locked out. Would I be able to get pointed in the right direction to resolve this?

**Comment by ansgarkorf** [comment]
Hi,
sorry to hear that. Maybe your mail was marked as spam. If info@mzio.io did not work please send an email with your user name to me: ansgar.korf@mzio.io

**Comment by dav7841** [comment]
Many thanks for the quick reply. I've emailed there.

**Comment by dav7841** [comment]
Hi, I'm just looking to follow up with this. I've sent emails but still waiting on resolving this issue. Would I be able to get some help with my user login?
