### ISSUE TITLE
Exported files showing empty "row identity (all IDs)"

### ISSUE THREAD

**Issue by apexagajjar** [mzmine/mzmine#2002]
### Basic information

* My operating system: Windows 10
* My mzmine version: 3.3.0

### I have followed these steps in sequence for mzML files.

Mass detection, ADAP chromatogram builder, chromatogram resolving using local minimum resolver, isotope pattern finder, Feature list filtering using feature list rows filters, alignment using join aligner, Gap filling using peak finder, ion identity network shows error, annotation using chemical formula prediction.
then exported CSV file is showing an empty column for "row identity (all IDs)"

![capture 4](https://github.com/user-attachments/assets/0a8a846a-bfac-4f98-a78c-5786146d3abb)
![Capture](https://github.com/user-attachments/assets/474aff5a-755b-443d-b783-5f5e3080e309)
![Capture1](https://github.com/user-attachments/assets/cc72dea4-2c25-4a85-80af-6bf5f8aa3063)
![Capture2](https://github.com/user-attachments/assets/b5388cbd-5fcd-41c0-a6a1-27935c16118f)
![Capture3](https://github.com/user-attachments/assets/4a75d8ed-c2bb-4bf1-9abd-9709e40c6093)

**Comment by ansgarkorf** [comment]
Hi,
your ion identity step does not contain any adducts. Click on "Reset positive/negative".
Also, please upgrade to version 4.2. We made a lot of fixes for the networking workflow since version 3.3
kind regards,
Ansgar
