### ISSUE TITLE
Error Exporting Feature Lists to CSV: Requires '{}' Pattern in Filename

### ISSUE THREAD

**Issue by ybsk0424** [mzmine/mzmine#2006]
![error message2](https://github.com/user-attachments/assets/6f05f37e-8485-4d6b-971f-4426dacb93ba)
[mzmine_0_0.log](https://github.com/user-attachments/files/16457243/mzmine_0_0.log)

Hi

I have a problem when I try to export to a CSV file. I am attempting to select those with a specific name from the feature list, but I keep encountering this error and I cannot get the data. Before I could get all the data together, but now it does not let me. Can you help me with this?

Operating System and Version:

Windows 11 Enterprise, 64-bit operating system, x64-based processor
12th Gen Intel(R) Core(TM) i7-1265U 1.80 GHz
16.0 GB RAM
Windows Feature Experience Pack
mzMine Version: mzMine 4.2.0

I have attached the screenshot, log file, and my project file. These are GC-EI Low resolution chromatograms.

Here is the link for the project file, it will expire in 1 week: (https://we.tl/t-DOv0XU6qNm)

I hope this information helps to diagnose the issue. Please let me know if any additional information is needed.

Thank you for your assistance!

**Comment by SteffenHeu** [comment]
Hi, 

do you want to export multiple feature lists at once or just a single feature list?

**Comment by ybsk0424** [comment]
I have 217 different chromatograms. For example, after adjusting them all with the local minimum feature resolver, I want to see them all in a single CSV file. However, it's giving me each chromatogram as a separate CSV file. Is there a way to combine them all into a single CSV file? Thank you.

**Comment by robinschmid** [comment]
This module exports ONE feature list to ONE csv file. If you select multiple feature lists you need to add {} as a name placeholder. 
Usually you would run alignment multiple feature lists to compare them across samples and get a single aligned feature list that you can export to one file. 

If you want to combine multiple csv files that can also be done easily in a small script downstream.
