### ISSUE TITLE
virutal drive as a input/output destination for mzmine?

### ISSUE THREAD

**Issue by marwa38** [mzmine/mzmine#2024]
* My operating system: windows
* My mzmine version: v4.2

Could I create temporoary folder on a virtual (NAS in dorrestein lab or google drive) as a temporary folder but aslo as input and output destination? I tried and I got an error that I haven't got before.
Kindly find screenshot below. 
![image](https://github.com/user-attachments/assets/3345a9c3-a967-4a48-919a-532e874bd0f0)

**Comment by SteffenHeu** [comment]
Hi, network drives may work but can also lead to issues. we dont usually recomment to load data from there. 
Also putting the temp folder on a network drive will lead to similar issues and will severly degrade your user experience.

**Comment by marwa38** [comment]
thanks :)
