### ISSUE TITLE
Spectral/Molecular Networking

### ISSUE THREAD

**Issue by dianacelit** [mzmine/mzmine#2028]
Operating system and version: Windows 11
Mzmine version 4.2.0

In previous versions of MZmine, the function I am trying to use was called MS/MS Spectral Networking. When attempting to use the current Spectral/Molecular Networking function in MZmine 4.2.0, I configured the parameters as usual. However, the generated MGF file does not contain the MS2 spectra. In earlier versions, the MGF file was correctly generated with MS2 data after running the MS/MS Spectral Networking function, but in this version, those data are not included.

![image](https://github.com/user-attachments/assets/75fd3110-22c6-47cb-a22f-5908fe129a26)

**Comment by SteffenHeu** [comment]
The spectral networking does not export any data, it applies the networking in mzmine. you can open the visualiser afterwards.

Are you perhaps looking for the export of the molecular networking files for gnps?

**Comment by dianacelit** [comment]
Hello Steffen:

I’ve tried generating the file in two different ways. The first was using the MGF file (ADAP), and for example, for a mass of 449, it should generate something like this (I worked on it in version 3.9):

BEGIN IONS
FEATURE_ID=276
PEPMASS=449.1948
SCANS=276
RTINSECONDS=348.664
CHARGE=2+
MSLEVEL=2
190.8687 1.5E1
194.2043 1.2E1
220.9096 2.4E1
229.1782 1.9E1
231.2761 3.0E1
247.1863 2.6E1
259.0072 1.2E1
287.0939 7.9E4
288.1028 4.7E2
289.3258 1.1E1
303.0471 2.4E1
305.2939 5.7E1
317.5382 3.3E1
335.0506 3.0E1
345.1160 2.8E1
347.6058 2.7E1
348.3102 1.4E1
349.1333 2.4E1
353.0164 2.1E1
359.3038 1.3E2
367.1231 2.2E1
367.7833 9.0E1
387.2751 9.9E1
389.1180 3.3E1
401.3255 3.0E1
403.3250 2.2E1
413.2874 2.6E1
414.5962 2.3E1
421.0225 1.7E1
431.2268 1.3E2
431.8600 1.3E1
449.3686 2.9E1
END IONS

In version 4.2, I get this:

BEGIN IONS
FEATURE_ID=103
PEPMASS=449
RTINSECONDS=242.973
SCANS=103
MSLEVEL=2
CHARGE=1+
449 2.9E4
450 5.1E3
451 4.4E3
452 4.3E3
453 2.8E3
455 8.5E3
END IONS

(I’m using a different chromatographic method, so the retention times change)

Morover, when I try to generate the file for GNPS, it comes out empty.

**Comment by ansgarkorf** [comment]
Can you please explain what you try to achieve and what steps/modules you have run? Ideally share some raw data and your batch file.
