### ISSUE TITLE
 Issue with Compound Annotation in MZmine 4.2.0 and 4.2.8 Using Spectral Library Search

### ISSUE THREAD

**Issue by ybsk0424** [mzmine/mzmine#2032]
I am trying to annotate a set of known compounds at different concentrations using the spectral library search in MZmine. The compounds include:

α-Pinene
Sabinene
Linalool
Methyl salicylate
Bornyl acetate
β-Caryophyllene
α-Humulene
δ-2-Carene (ISTD)
Despite testing multiple recommended libraries, I am unable to successfully annotate these compounds. I am working with GC-EI (low-resolution) data, and the spectral library search feature in MZmine does not seem to produce any matches. I tried both Mzmine 4.2.0 and 4.2.8.

Details:

Operating System: Windows 11 Enterprise, 64-bit operating system, x64-based processor
Processor: 12th Gen Intel(R) Core(TM) i7-1265U 1.80 GHz
RAM: 16.0 GB
MZmine Version: MZmine 4.2.0
Steps Taken:

Project File:
You can access the project file through the following link (valid for 1 week): (https://we.tl/t-UAGRmLXVE2)

Could you please provide assistance or guidance on how to resolve this issue? Are there specific libraries or settings that are better suited for GC-EI (low-resolution) data in MZmine?

Thank you for your help.

**Comment by ansgarkorf** [comment]
Can you please share a log file and a batch file that contains all your steps?
Please make sure the libraries actually contain the compounds you are looking for. Furthermore, if the compounds are part of the library, I recommend to double check if your sample prep and analytical method fit the library spectrum, which can be different due to derivatization.

**Comment by ybsk0424** [comment]
Hi, here is the batch file : https://we.tl/t-JwaV8O0Bah
[mzmine_0_0.log](https://github.com/user-attachments/files/16610845/mzmine_0_0.log)
I tried with many different libraries and I am sure these compounds are part of the libraries. These are very basic compounds because of that I used them as a control. Thank you.

**Comment by ansgarkorf** [comment]
Hi,
your batch does not have a feature resolver step nor a spectral deconvolution step. The library search module requires you to run these first. To avoid such a problem, please use the mzwizard, add your files and select create batch and improve from there.

**Comment by ansgarkorf** [comment]
Did you have success using the wizard?

**Comment by ybsk0424** [comment]
I am facing persistent issues with annotation in MZmine, and despite multiple attempts, I am unable to achieve the expected results. Initially, I intended to perform a simple control annotation using the following compounds:

α-Pinene
Sabinene
Linalool
Methyl salicylate
Bornyl acetate
β-Caryophyllene
α-Humulene
δ-2-Carene (ISTD)
However, none of these compounds were identified correctly using the spectral library search in MZmine.

Additionally, when attempting to annotate my actual samples, my internal standard δ-2-Carene is consistently identified as Terpinolene (similarity score: 0.919) across all searches. I suspect this issue might be related to the spectral libraries I have tried. I have used all the libraries recommended on the MZmine website, but the problem persists with δ-2-Carene being misidentified as Terpinolene.

My goal is relatively simple: I need to process 217 chromatograms by performing annotation, retention time alignment, chromatogram shift correction, background noise removal, and then export the results to a CSV file. However, despite spending over a month working with MZmine, I have been unable to obtain reliable results.

**Comment by ansgarkorf** [comment]
It sounds you made some progress. I assume you now used the mzwizard to create a batch? What steps did you do to optimize your processing method? The mzwizard will give you a good starting point, but will not give you perfect results out of the box. 
To conclude, your original issue was solved. Therefore, I will close this issue now.

**Comment by ybsk0424** [comment]
Yes I used mzwizard and batch queue was imports ms data, mass detection, chromatogram builder, local minimum feature resolver, retention time correction, GC-EI spectral decon, GC aligner, Feature list rows filter, duplicate peak filter and spectral library search.  We couldn't fully understand what GC EI spectral deconvolution does. In the lab where I work, everyone analyzes GC chromatograms using a very very old version of ChemStation, meaning they manually do everything that MZmine can do automatically. So, MZmine is a huge innovation for us, and we're very grateful for it. However, we’re having trouble understanding spectral deconvolution. For example, when we use it, it seems like we lose a large portion of our peaks, which I don't think should be happening.
