### ISSUE TITLE
Mac user problems: I can't install MZmine4 or import my MS data in MZmine3

### ISSUE THREAD

**Issue by diaorao** [mzmine/mzmine#2033]
### Basic information

* My operating system and version: Mac book air2020, Intel core i5,  Sonama 14.6.1
* My mzmine version: version4.2 and version 3.8

### What happened
I have two problems:
The first problem is that I tried several times to install the latest MZmine version but all failed, my computer showed that it does not support this application, and I asked the Apple technician for help and they said there is nothing wrong in my computer setting.  Here is the picture when the problem happens:
<img width="521" alt="截屏2024-08-13 15 56 07" src="https://github.com/user-attachments/assets/b54df189-ca1a-405d-8547-061ca1e514e5">

the second problem is that I can successfully download and install MZmine3, but it keeps reporting error when I drag in my MZ data or import it. My data has already converted into MzML fomat.
<img width="486" alt="截屏2024-08-13 12 40 19" src="https://github.com/user-attachments/assets/38a5cead-13c9-4d5a-b98a-cefcf6f5d3ce">
 
If you are able to help me resolve this issue, it would mean a great deal to me. So thanks in advance！

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the mzmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by SteffenHeu** [comment]
Hi,

unfortunately x86 Macs (Intel CPU) are not supported anymore, because we have no build pipeline on for it on github. MZmine 4.08 or 4.03 should be the last working version, please try those.

Otherwise you can compile MZmine on your pc from source, that should work.

Sorry for the inconvenience

**Comment by diaorao** [comment]
Hi Steffen, thank you so much for your advice, now its working ;)
