### ISSUE TITLE
Maximum operating quantity

### ISSUE THREAD

**Issue by ashin947** [mzmine/mzmine#2039]
### Basic information

* My operating system and version: windows10
* My mzmine version: mzmine4.2.0

### What happened
Hi 

What is the maximum sample size for the program to run? Or it depends solely on the running memory of the computer. I have a computer with 256GB RAM that still cannot run 500 raw data files (about 120MB per file). Is there any way we can solve this problem?

Thanks

**Comment by ansgarkorf** [comment]
Depends on your processing settings and SSD drive. We have users processing 1000s of samples. Please share more details on your current workflow or even better a batch file.

**Comment by ashin947** [comment]
[batch.txt](https://github.com/user-attachments/files/16656691/batch.txt)

This is the batch file I am using. We copied the raw data file into 500 copies for trial operation

**Comment by ansgarkorf** [comment]
You should remove the Same RT and m/z range gap filler module from your batch. You are using 2 different gap filling algorithms in your batch, which is unnecessary. I recommend to use the Peak Finder (multithreaded) only. Removing that module should fix your performance bottleneck. 
Did you start building your batch from the mzwizard?

**Comment by ashin947** [comment]
project -> Bacth mode，Select modules

Is there a significant difference between these two creation methods?

**Comment by ansgarkorf** [comment]
Yes, the mzwizard helps you setup the modules. You will get something like in the screenshot. Please let me know if your performance improves for your 500 files.
<img width="943" alt="image" src="https://github.com/user-attachments/assets/1b9ef6a7-0d88-4109-91f2-188fd52a743d">

**Comment by ashin947** [comment]
Thank you very much for your answer. I will try to remove the Same RT and m/z range gap filler module first.

**Comment by ansgarkorf** [comment]
did it help?

**Comment by ashin947** [comment]
Relieve some memory pressure, but still cannot run 500 samples. We tried to convert the raw format file to mzXML format and it became runnable. I think it's because the file size was reduced by 5 times after the format conversion

**Comment by ansgarkorf** [comment]
It should run best with mzML files.

**Comment by ashin947** [comment]
I see  ，Thanks
