### ISSUE TITLE
Error during "Create batch"

### ISSUE THREAD

**Issue by SonamTam** [mzmine/mzmine#2041]
### Basic information: Error of task Batch step 6/20

* My operating system and version: Windows 11
* My mzmine version: mzmine 4.1.0

### I am trying to create a batch for a group of DIA runs. The data files were obtained by UPLC- QTOF in positive mode. I have already converted them to .mzML format from the Waters .raw format. I am using the processing wizard, and every time I try to create a batch I run into an error saying "Error of task Batch step 6/20: Invalid parameter settings for module Smoothing: [At least 1 feature lists must be selected]. Just to check, I also tried removing the smoothing parameter, but then it gave me another error:  "Error of task Batch step 6/19: Invalid parameter settings for module Local minimum feature resolver: [At least 1 feature lists must be selected]. I did the "check" before trying to create a batch, which tells me that "all parameters are set correctly". 
Also I am having some problems saving the project. 

[MZMine error.pptx](https://github.com/user-attachments/files/16661637/MZMine.error.pptx)

**Comment by ansgarkorf** [comment]
Hi,
can you share the log file and the batch file? If you could share also one or two files the chance of solving your problem will be much higher.

**Comment by ansgarkorf** [comment]
Hi,
the log file already gives some good indication. It seems there is a raw data conversion issue. The scans are not sorted in retention time order. How did you convert the data to mzML? 
You can get the batch file here:
<img width="939" alt="image" src="https://github.com/user-attachments/assets/56f94753-5d9b-4c51-8d15-7241667cb70c">

For raw data upload you can use any provider you want, e.g. google drive.

**Comment by SonamTam** [comment]
Hi,
I used MSConvert to convert the .raw (Waters) data file to mzML. I have attached the batch file below and a BOX link to one of the raw data file. Hope this helps solve the problem.

[20240816_batchfile.zip](https://github.com/user-attachments/files/16676546/20240816_batchfile.zip)
https://app.box.com/s/rs6l6sep3ii9hjcedc2h819wv0dszhor

**Comment by ansgarkorf** [comment]
Hi,
I looked into your data and the scan numbering is all over the place. You can check for yourself when looking at the file with the raw data overview. Multiple scans get the same scan number. For now the recommended way to convert waters data to mzml is using an official waters tool you can find here: https://microapps.on-demand.waters.com/home/showmarkdown/data-as-a-product
Please also see our documentation: 
https://mzmine.github.io/mzmine_documentation/data_conversion.html#waters

We are working on a solution to solve this conversion problem internally. Maybe this will come with version 4.3
For now, please try to use the waters converter.

**Comment by SonamTam** [comment]
Hi,

Thank you for your advice. I converted the data files to mzml using Waters data connect. It worked in the sense that I can create a batch and run it and also get some output files, without running into an error. I still have a concern over how my files look like in the raw data overview. It is still showing the same precursor m/z for all the scans. I have attached the log file, batch file and the screenshots below. 

Thank you for your time. Really appreciate it!
Sonam

[MZMine error_2.pptx](https://github.com/user-attachments/files/16679818/MZMine.error_2.pptx)
[20240820_mzmine_0_0.txt](https://github.com/user-attachments/files/16679822/20240820_mzmine_0_0.txt)
[20240820_batchfile.zip](https://github.com/user-attachments/files/16679839/20240820_batchfile.zip)

**Comment by ansgarkorf** [comment]
Can you share a correctly converted file?

**Comment by SonamTam** [comment]
Its bigger than 2 GB. So, my free Box account doesn't work anymore. Can you open this sharepoint file?
https://uconn-my.sharepoint.com/:u:/g/personal/sonam_tamrakar_uconn_edu/EfInAHpFpnBOjONikGOQBtYBEvAJtYvxyVTxMTI0vM_0DA?email=notification%40github.com&e=N3vkfO

**Comment by ansgarkorf** [comment]
Sorry, I cant access the file. 
The precursor mass should be the center of your MS2 mz range. When you select an MS2 scan you should see a grey marker in the spectrum. That is your Q isolation window.

**Comment by SteffenHeu** [comment]
> Sorry, I cant access the file. The precursor mass should be the center of your MS2 mz range. When you select an MS2 scan you should see a grey marker in the spectrum. That is your Q isolation window.

exactly. DIA acquisition has no real precursor ion selection, so the precursor m/z column shows the center m/z the quad is set to.
What would you expect in that column @SonamTam?

**Comment by SonamTam** [comment]
Hi,

Okay so the reason I am seeing the same the precursor ion, 1025.00, all the way is because it is choosing the center of my MS2 range, right? Does this also explain my MS/MS scatter plot which is a straight line along 1025.00? Is this expected for all DIA runs?

Thanks,
Sonam

**Comment by ansgarkorf** [comment]
This is expected, since you dont pick a precursor in DIA.

**Comment by SonamTam** [comment]
Great! Thanks for clarifying that. I hope to explore mzmine further for my data analysis. Thank you for you help.

**Comment by ansgarkorf** [comment]
you're welcome :-)
