### ISSUE TITLE
the similar issues on peak area integration

### ISSUE THREAD

**Issue by ashin947** [mzmine/mzmine#2042]
[mzmine integration issue.pdf](https://github.com/user-attachments/files/16705133/mzmine.integration.issue.pdf)
* My operating system and version:windowns
* My mzmine version: 4.2.0

Hi, everyone, I do not know if anybody observing the issues on the peak integration. I run 20 data files by Thermo QE-Plus mass spec and then by MZMINE software. One feaure ,m/z=782.56878 RT=1.23 min positive mode, by MZMINE was wrongly skewed integrated, which shows lots of scan points were missing and integration area was much lower. However, all 20 files were good when integration on Thermo Xcalibur browser and data acquistion was absolutely fine= no any data scan missing. So the problems happened on MZMINE.  It could be poor scan mass accuracy, however, the mass accuracy was 3 in raw mass spec data and 8 ppm was used for mzmine processing. So it is unlikely to be the reason of mass accuracy. Does anyone come across the similar issues on peak area integration?

**Comment by ansgarkorf** [comment]
Hi,
difficult to help without seeing data. 
As a first step you can easily find out if mass accuracy is the problem by allowing wider tolerances.

**Comment by ashin947** [comment]
![1](https://github.com/user-attachments/assets/f351e09e-9abf-444c-b403-8dd12d7a601c)
![2](https://github.com/user-attachments/assets/9d30ae1c-6124-4fb0-83f9-3bc728bbb449)
![3](https://github.com/user-attachments/assets/50391d68-b6c7-43a5-b48e-a564deb7c0ff)
![4](https://github.com/user-attachments/assets/f41b8251-9eca-4679-86d6-703c497cebbf)
I have found a few pictures, hoping they can express my meaning

**Comment by Kirsteen426** [comment]
![picture1](https://github.com/user-attachments/assets/b0676367-b6ca-459e-b874-8b67988b1a2a)
![picture2](https://github.com/user-attachments/assets/1a28dd0b-2d76-42dd-98f7-ae829e04eee9)
![picture3](https://github.com/user-attachments/assets/c3050205-1233-4950-a1cf-c085ac26a8e8)

**Comment by ansgarkorf** [comment]
Very hard to see, but is this polarity switching data?
If yes, please make sure you have enough data points per peak. 
We should check if the manual integration tool properly works for polarity switching.

**Comment by Kirsteen426** [comment]
[mzmine integration issue.pdf](https://github.com/user-attachments/files/16698321/mzmine.integration.issue.pdf)

Dear all, have a look the PDF. The data is acquired by polarity switching, which didnot miss the scan point. As can be seen from Thermo Xcalibur browser.

**Comment by Kirsteen426** [comment]
> Very hard to see, but is this polarity switching data? If yes, please make sure you have enough data points per peak. We should check if the manual integration tool properly works for polarity switching.

MZMINE never make mess of the peak integration if the parameters stetting is correct? Thank you very much for the help.

**Comment by ansgarkorf** [comment]
Can you share one of the raw files where the integration is not good?

**Comment by Kirsteen426** [comment]
> Can you share one of the raw files where the integration is not good?

Thank you for the reply. For this case, raw files integration are good. If the raw files integration is bad, I would not expect MZMINE to rectify the bad integrations.

**Comment by Kirsteen426** [comment]
> Dear all, have a look the PDF. The data is acquired by polarity switching. The scan point is really fine for this peak, no missing no lacking etc, as can be seen from Thermo Xcalibur browser. Really want to figure out why MZMINE integration is poor. Thanks.

Dear all, have a look the PDF. The data is acquired by polarity switching. The scan point is really fine for this peak, no missing no lacking etc, as can be seen from Thermo Xcalibur browser. Really want to figure out why MZMINE integration is poor. Thanks.
[mzmine integration issue.pdf](https://github.com/user-attachments/files/16698807/mzmine.integration.issue.pdf)

**Comment by Kirsteen426** [comment]
> Very hard to see, but is this polarity switching data? If yes, please make sure you have enough data points per peak. We should check if the manual integration tool properly works for polarity switching.

Dear all, have a look the PDF. The data is acquired by polarity switching. The scan point is really fine for this peak, no missing no lacking etc, as can be seen from Thermo Xcalibur browser. Really want to figure out why MZMINE integration is poor. Thanks.
[mzmine integration issue.pdf](https://github.com/user-attachments/files/16698811/mzmine.integration.issue.pdf)

**Comment by robinschmid** [comment]
@Kirsteen426 thanks for filing an issue. In order to work on it and solve it, we need a raw data file and the batch processing configuration. The batch should contain all the steps needed to reproduce the issue. 

I guess your issue is really with the manual reintegration pane and not so much with the automatic integration during batch processing with chromatogram builder and feature resolving?

Best
Robin

**Comment by ashin947** [comment]
I have sent the file to this address  
https://github.com/ashin947/raw-data.git
![image](https://github.com/user-attachments/assets/d3e1aacc-333a-4739-afc9-607f96f69db8)

**Comment by robinschmid** [comment]
in the raw data visualizer, you have to select the polarity to show below the chromatogram plot. 

![image](https://github.com/user-attachments/assets/e0a2e09d-8f76-4ef2-82be-f529d30c0ad6)


During processing you need to set the scan filter to only use one polarity. This can be done in the mzwizard:
![image](https://github.com/user-attachments/assets/ad75cd6b-51cb-4fe5-88be-84ddb51fe07a)


Or in the chromatogram builder to build chromatograms for positive mode first and then negative mode second.
![image](https://github.com/user-attachments/assets/226fa850-cc7f-41b4-96f1-a4486396373b)

**Comment by ashin947** [comment]
![image](https://github.com/user-attachments/assets/d7eb4c5d-f7c0-433c-8079-44dbedd13acc)
Thank you very much for your reply, but I'm not sure if it's just a display reason. When I double-click on Area, S1 is missing scan points (FIG A) compared to S2. Opening TIC Visualizer is indeed normal (FIG B). Is it related to the deviation of mz scan points?

**Comment by ashin947** [comment]
Thanks, this issue has been solved.
