### ISSUE TITLE
baseline correction module is not working in mzmine 4.2.0 version

### ISSUE THREAD

**Issue by Himanshudhanawat** [mzmine/mzmine#2047]
i am facing to use the base line correction module. please see asap

**Comment by robinschmid** [comment]
Please follow the issue reporting guidelines and describe / attach all information needed:

### Basic information

* My operating system and version:
* My mzmine version: 

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the mzmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

**Comment by Himanshudhanawat** [comment]
Edition	Windows 11 Home Single Language
Version	23H2
Installed on	‎9/‎30/‎2022
OS build	22631.4037
Experience	Windows Feature Experience Pack 1000.22700.1027.0
mzmine 4.2.0

i am unable to use the baseline correction module in mzmine 
![Screenshot 2024-08-27 154016](https://github.com/user-attachments/assets/8f81105e-7c37-4336-8e0c-b1005d41f8c5)

**Comment by SteffenHeu** [comment]
https://github.com/mzmine/mzmine/issues/1901

**Comment by Himanshudhanawat** [comment]
provide me the sample file to perform the data preprocessing
