### ISSUE TITLE
MSE, precursor and fragment error

### ISSUE THREAD

**Issue by Melakail** [mzmine/mzmine#2059]
### Basic information

Windows 11
Mzmine4 

### What happened
Using the qtof and DIA processing wizard, I generated mgf files and quant tables for waters MSE data. However, the precursor masses dont align to fragment spectra (625 is repeated continuously as the precursor mass).  MSE data was in profile mode which was centroided and converted to mzML using waters data connect. I would like to know how I can rectify this issue so I can use it downstream for statistics plus annotations such as SIRIUS in silico. I have attached an example sample. This is the first time using this service so hopefully I have provided adequate detail. 

[https://drive.google.com/drive/folders/15oBoJZnzuCiMdJr25ympKGpqNjHSy8KK?usp=drive_link](url)

Thanks
Benjamin

**Comment by SteffenHeu** [comment]
Hi @Melakail 

the download link does not for me, the access is restricted.

The 625 is always reported as a precursor mz in the MSe scans, because it is probably the center of the isolation window of the quadrupole when you run MSe analysis. 

Is it also reported as precursor mz in the sirius export, e.g. the mgf file?

**Comment by Melakail** [comment]
Hi Steffen

No the mgf file output seems fine and I can run it through SIRIUS no problem. I was trying to make sense of this 625 that kept popping up on mzmine. Is the link still restricted?

**Comment by SteffenHeu** [comment]
Hi,

if the Sirius export works fine, everything works as expected. The precursor mass being the same for all scans is just how MSe works. What would you expect to see there instead?
