### ISSUE TITLE
mzmine 4.1.0 chromatogram resolving  No Response!!

### ISSUE THREAD

**Issue by Sclllllll** [mzmine/mzmine#2064]
### Basic information

* My operating system and version:window11
* My mzmine version: mzmine 4.1.0

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the mzmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

When I ran the local minimum reoslver in the chromatogram resolving, there was no response after setting the parameters. The prompt in the lower left corner is always: Setting parameters for module Local minimun feature resolver. This situation has been going on for a week. Please help me solve it. I tried the latest version, too.
 A screenshot is attached below.
![1](https://github.com/user-attachments/assets/0f71ad64-5843-4d51-a351-80af120306f9)
![2](https://github.com/user-attachments/assets/52789500-b9ee-43b0-920f-abc1aa9c4f2c)

**Comment by ansgarkorf** [comment]
Hi,
from the screenshot it looks like your license has expired. Please send an email to info@mzio.io to clarify your status as an academic.
kind regards,
Ansgar
