### ISSUE TITLE
Error: "Error of task importing raw data file...:No scans found"

### ISSUE THREAD

**Issue by KarenF21** [mzmine/mzmine#2065]
**Basic information**

My operating system and version: Windows 11
My MZmine version: 3.9.0

**What happened**

I work with AB Sciex, system 320 QTRAP LC-MS/MS. I conducted some analyses and imported the data from the equipment in the .WIFF and .WIFF.SCAN formats. I converted the data to mzML using MSconvert, following the recommendations. However, when importing this data into MZmine, the action is canceled and the following message appears: "Error of task importing raw data file...: No scans found."

These are the WIFF data and the converted data: https://drive.google.com/drive/folders/1biQgWp0-tzL0V2HiYxAunc3Dc5do1YAn?usp=sharing

When I open it in seeMS (Proteowizard), I can observe the scans.

Could you help me understand if the error is in the data conversion?

Thank you for your help.

**Comment by SteffenHeu** [comment]
Hi, i think the particular format of mzml is not supported unfortunately. When using the Sim As Spectra or SRM as spectra options, you get something in mzmine, but i think the data is being misinterpreted for that. We will put more work into a TQ workflow in the future, but it is currently not easy to process MRM data. Sorry.
