### ISSUE TITLE
Consultation on the parameters of the 'spectral library search' module

### ISSUE THREAD

**Issue by ashin947** [mzmine/mzmine#2071]
Hi, l came cross the MS2 spectral matching or searching problems, for instance, L-arginine has good MS2 spectral by QE-pluspositive mode acquisition. Fragments like m/z 158.0925, 130.0964,116.0706 ,70.0652 etc. were well generated by HCD collision of L-Arginine, However, mzmine did not recoanize L-arginine ms2 or has no match to Arginine or no match with m/z 175.1190 (l can see it in the feature list). We set quite large m/z tolerance range. Can you kindly work out the possible reasons? Thanks

![image](https://github.com/user-attachments/assets/64592ac1-11a1-438e-8a07-48a4167a4ec1)
![image](https://github.com/user-attachments/assets/034201be-37c1-4d7d-8fac-23f56e66f693)

**Comment by robinschmid** [comment]
Did you create the batch with the mzwizard? 
The feature resolver step has MS2 grouping activated with wide enough tolerances?

**Comment by ashin947** [comment]
Yes, I can match some MS2. Do we need to expand some mz tolerances，such as 20ppm.
![image](https://github.com/user-attachments/assets/5b05b67d-dceb-4acc-98b5-249cabd5e1ca)

**Comment by Kirsteen426** [comment]
> Did you create the batch with the mzwizard? The feature resolver step has MS2 grouping activated with wide enough tolerances?

10 ppm mz tolerance is really wide, dont you think it is enough?

**Comment by robinschmid** [comment]
Quadrupol isolation of precursor ions is usually not very narrow thats why 0.01 or even more is good. Sometimes the data is not correctly recalibrated leading to difference between measured mz and precursor mz in MS2 metadata.
You can also try to change the retention time filter and allow wider window.

**Comment by Kirsteen426** [comment]
> Or maybe your mass detection on MS2 is too high of a noise level. You can use a factor of lowest signal with 2 or even just 1 to include all signals for now

Thank you, is that possible that you give a try? I will upload one MS2 raw data and batch file.  We tried many parameters and have no luck unfortunately.
