### ISSUE TITLE
Error loading saved standalone mzmine file

### ISSUE THREAD

**Issue by jfmonbulusal** [mzmine/mzmine#2094]
### Basic information

Windows 10 (64bits) operating mzmine 3.9.

### What happened

When trying to open a standalone saved file, it prompts the following error and does not perform the loading:
2024-09-20 11:15:47 FINEST io.github.mzmine.gui.MZmineGUI displayMessage Error - Could not identify the data type needed for import of n files=17 - null
2024-09-20 11:15:47 SEVERE io.github.mzmine.modules.io.import_rawdata_all.AllSpectralDataImportModule runModule Could not identify the data type needed for import of n files=17.  C:\Users\jfmon\AppData\Local\Temp\mzmine_msdatafiles_temp921199070776519868\msdatafiles\inmic06.raw

Nonetheless the original raw data files, that were read in the saved version, remain in the same folder (they are in a OneDrive synchronized folder though), and this error has only recently appeared.

Thanks in advance and best regards.

**Comment by SteffenHeu** [comment]
Hi @jfmonbulusal,

in a standalone project, the raw files are cpoied into the project file to make it portable. If an error occurs during loading/saving (e.g. mzmine closed or no more disk space) then the copying does not work and the project file is corrupted (this is why we recommend to set the temp folder to a place with enough space). In your case with all the files in a constant position on a onedrive, a flexible project is recommended. 

What you can **try** to fix the project is:

- open the .mzmine project as a zip folder (e.g. 7zip). Check if all the files are present. if not, copy them there manually.

or:

- open the project as a zip, open the "raw_data_import_batch.xml" and edit **all** the file paths to the raw files to the onedrive folder, delete the "STANDALONE" file

(i recommend the first option)

**Comment by jfmonbulusal** [comment]
Thank you doubly since both approaches worked perfectly. I realised the raw files not present in the standalone file once I opened as a zip (even though my SSD disk should have had enough space... probably, I closed the interface before fully saved). Best regards.

**Comment by mariachalk** [comment]
First option worked. The msdatafiles folder was missing when opening the zip folder. Creating the folder and copying the files as you suggested, fixed it.

Thank you vey much.

Best regards
