### ISSUE TITLE
MacOS is not supported by Bruker Daltonic

### ISSUE THREAD

**Issue by MicroEco** [mzmine/mzmine#2113]
### Basic information

* My operating system and version: MacOS Sonoma
* My mzmine version: mzmine 4.3.0

### What happened
* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the mzmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed
I tried to import Bruker tims TOF .tdf file but it failed and got error message "MacOS is not supported by Bruker Daltonic". I used mzmine for Windows before, and it worked fine with Bruker vendor format data. Any suggestion about how to import Bruker vendor format raw data to mzmine on Mac?
<img width="1505" alt="Screenshot 2024-10-01 at 18 45 59" src="https://github.com/user-attachments/assets/e6eabf9b-6bdc-4ccc-93fa-83d73101391d">
[QC1 -rep4_2_1_4836.d.zip](https://github.com/user-attachments/files/17214450/QC1.-rep4_2_1_4836.d.zip)

**Comment by MicroEco** [comment]
raw data: https://drive.google.com/drive/folders/141OeYlswrCLCThY8f0WfY8Lpe2YfOSCy?usp=drive_link

**Comment by ansgarkorf** [comment]
Hi,
as the message indicates, it is simply not supported for macOS by Bruker, nothing we can do. 
You can run windows in a VM in parallel on your mac. I do that as well for Bruker data on my mac.
