### ISSUE TITLE
PCA statistic

### ISSUE THREAD

**Issue by zdenka2** [mzmine/mzmine#2128]
### Basic information

* My operating system and version: Windows 10 Enterprise LTSC, 1809 (OS Build 17763.2686) 
* My mzmine version: 4.3.0

### What happened
Hello, dear mzmine3 developers,
First, I want to commend you on creating such excellent software.
I have problem with PCA statistic. I made alagment of feature lists, after that I woul like to create PCA plot, but this error was appeared: 
![Snímek obrazovky 2024-10-14 143631](https://github.com/user-attachments/assets/ce08002a-c4c7-46ab-a225-ea48909d614d)
I check sample metadata, but informations abou sample_type were there. Is there any other option to set sample type? 
![Snímek obrazovky 2024-10-14 144149](https://github.com/user-attachments/assets/0d35f983-344f-4d2c-9829-7c3cb70da0c8)
I can´t find any information about setting of PCA statistic in mzMine.
Thanks you
Zdenka

**Comment by robinschmid** [comment]
Thanks for reaching out can you post your log file?

**Comment by robinschmid** [comment]
You can try the latest development release from the releases page. This issue should be resolved in the next release.
