### ISSUE TITLE
How to download mzmine in mac system 

### ISSUE THREAD

**Issue by Himanshudhanawat** [mzmine/mzmine#2131]
I unable to install mzmine at my mac system

**Comment by Himanshudhanawat** [comment]
how to install mzmine in mac system 
can you provide the better file for application 
i used that file which is on github but that file is not working

**Comment by rmbluee** [comment]
I'm having the same issue

**Comment by ansgarkorf** [comment]
Hi
Please follow the guideline to report issues.
What Mac do you use? What macOS version do you use?

**Comment by ansgarkorf** [comment]
@Himanshudhanawat did it work following the documentation?
