### ISSUE TITLE
The trial pro has expired. 

### ISSUE THREAD

**Issue by woshibaipiaogua** [mzmine/mzmine#2140]
### Basic information

* My operating system and version:Windows 11
* My mzmine version: Mzmine4.3.0

### What happened

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the mzmine modules you used. 
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

<img width="148" alt="屏幕截图 2024-10-16 163558" src="https://github.com/user-attachments/assets/7a1aaf11-5b3a-461d-9693-9a40f70620b5">

The trial pro has expired. Some features are unavailable. How can I reactivate them? Additionally, what features are available to non-pro users, and which features are only accessible to pro users?

**Comment by ansgarkorf** [comment]
Hi,
please get in touch with us via info@mzio.io to sort out your user account.
