### ISSUE TITLE
The exported data is empty

### ISSUE THREAD

**Issue by Yuan-666-lab** [mzmine/mzmine#2160]
### Basic information

* My operating system:Windows 11 
* My mzmine version: 3.6.0
My problem:
1.When I need to export the feature list, the 'file name' cannot be selected. Do I need to create the 'file name' first?
2. And the data I exported is empty. The data I selected for export is GNPS data.
<img width="960" alt="微信图片_20241023160004" src="https://github.com/user-attachments/assets/1a644e23-281c-4ebf-9cc1-57143516d957">
![image](https://github.com/user-attachments/assets/d154c6c3-398a-422a-a54d-a7dd51b3b6da)

My parameter setting steps:
I have followed these steps in sequence for mzML files. Mass detection, ADAP chromatogram builder, chromatogram resolving using local minimum resolver, isotope pattern finder, Feature list filtering using feature list rows filters, alignment using join aligner, then exported feature list, Molecular networking files (e.g., GNPS, FBMN, IMN, MetGem),  feature list is 'filtered Aligned feature list filtered',filter rows is 'MS2 AND ION IDENTITY' 
![image](https://github.com/user-attachments/assets/d6cd08b6-8e9e-4ede-8576-399a35a71951)
![image](https://github.com/user-attachments/assets/ce8bea1f-f690-40c2-8e12-92237d38118f)
![image](https://github.com/user-attachments/assets/aac3cc6a-3297-41dc-8a8a-c802fc849033)
![image](https://github.com/user-attachments/assets/ca7d62db-3e75-4fb0-814c-d50e56a84b28)
![image](https://github.com/user-attachments/assets/aba906f1-f655-4d81-96b7-0e1128916cc5)
![image](https://github.com/user-attachments/assets/2a6a8e38-23a6-4725-ae12-bca50f4db2d0)
![image](https://github.com/user-attachments/assets/3d538d19-b75c-4506-9dd4-b17ff8074994)

**Comment by ansgarkorf** [comment]
Hi,
please try updating to the latest version 4.3 and try using the mzwizard.
When you set the file name for the export, make sure to use the "Select" option of the parameter.

**Comment by Yuan-666-lab** [comment]
> 您好，请尝试更新到最新版本 4.3 并尝试使用 mzwizard。当您为导出设置文件名时，请确保使用参数的 “Select” 选项。

Yes, I clicked "Select", but I can't make a selection. Is this because of the version problem? Is there anything wrong with my setting parameters?

**Comment by Yuan-666-lab** [comment]
Yes, I clicked "Select", but I can't make a selection. Is this because of the version problem? Is there anything wrong with my setting parameters?


---- Replied Message ----
| From | Ansgar ***@***.***> |
| Date | 10/23/2024 17:08 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [mzmine/mzmine] The exported data is empty (Issue #2160) |

Hi,
please try updating to the latest version 4.3 and try using the mzwizard.
When you set the file name for the export, make sure to use the "Select" option of the parameter.
