### ISSUE TITLE
An exclamation mark appears in front of the imported data

### ISSUE THREAD

**Issue by Yuan-666-lab** [mzmine/mzmine#2162]
Does an exclamation mark in front of imported data affect data processing and export?

* My operating system: windows 11
* My mzmine version: 4.3.0

![image](https://github.com/user-attachments/assets/c0464adc-ea2a-4aeb-ab26-1e8e48b88b1d)

**Comment by SteffenHeu** [comment]
Hi, 
please refer to the documentation. Hovering over the warning sign will give you a tooltip and a description of what is happening. 
https://mzmine.github.io/mzmine_documentation/troubleshooting.html#scans-were-recognised-as-empty

https://mzmine.github.io/mzmine_documentation/troubleshooting.html#zero-intensity-values-in-scans

**Comment by Yuan-666-lab** [comment]
> Hi, please refer to the documentation. Hovering over the warning sign will give you a tooltip and a description of what is happening. https://mzmine.github.io/mzmine_documentation/troubleshooting.html#scans-were-recognised-as-empty
> 
> https://mzmine.github.io/mzmine_documentation/troubleshooting.html#zero-intensity-values-in-scans

<img width="430" alt="c225d1fc00d296a2715bed7ccb23e50" src="https://github.com/user-attachments/assets/f0d45a4e-9386-4d67-a131-e1c77a4d950d">
Thank you for your suggestion. How can I solve this problem?

**Comment by robinschmid** [comment]
The message is quite clear that this is only a warning. Nothing to worry about if you did everything right on your side. 
Just check if the data conversion had some noise threshold that you could remove
