### ISSUE TITLE
Error in imported data

### ISSUE THREAD

**Issue by Yuan-666-lab** [mzmine/mzmine#2163]
This exclamation point appeared when I imported data. Secondly, I converted it with the latest version of msconvert software, and the result is still the same. How to solve this kind of problem?

* My operating system: windows 11
* My mzmine version: 4.3.0

![image](https://github.com/user-attachments/assets/f43b038a-6f3a-4d22-8ce5-62ae742056da)

**Comment by robinschmid** [comment]
Please do not repost issues. It was addressed here #2162 
Also please add more work into your issues like: what instrument, what version of msconvert, what were your settings, ...

Please read the message - it is only a warning but may not be a real issue.
