### ISSUE TITLE
Data cannot be exported

### ISSUE THREAD

**Issue by Yuan-666-lab** [mzmine/mzmine#2166]
### Basic information

* My operating system: windows 11
* My mzmine version: 3.6.0

![image](https://github.com/user-attachments/assets/d0741a12-28e5-4fc9-bf30-d52e91bc9212)

How do I solve this problem when I want to export GNPS data?

**Comment by SteffenHeu** [comment]
![grafik](https://github.com/user-attachments/assets/f1f565c0-b64b-47e8-8505-78d76404667e)

**Comment by Yuan-666-lab** [comment]
Thank you very much, this problem has been solved. But the exported data is empty. What is the reason?

![image](https://github.com/user-attachments/assets/fb87d718-8d5a-463f-9355-57cbc0fa4cd4)

**Comment by robinschmid** [comment]
Please check if your feature list contains rows and if your rows have MS2 spectra. You can add columns at the top right corner + button and see the number of fragment scans. 
Or use the feature list rows filter module to only retain rows with MS2 fragmentation.

GNPS needs MS2 spectra.
