### ISSUE TITLE
The exported data is empty and the FBMN analysis fails

### ISSUE THREAD

**Issue by Yuan-666-lab** [mzmine/mzmine#2167]
* My operating system: windows 11
* My mzmine version: 3.6.0

![image](https://github.com/user-attachments/assets/411f7230-18f8-400e-b723-2a25a9e1df4b)

![image](https://github.com/user-attachments/assets/0ac2668c-5b68-4838-a45a-1ff862ed0854)

When I export data using GNPS mode, the exported data is empty and FBMN displays an error after running for a few minutes. What is the reason and how can I solve it?

**Comment by SteffenHeu** [comment]
Hi, 
please use the search function before opening an issue every few minutes. This has been described multiple times.

**Comment by Yuan-666-lab** [comment]
> 您好，请在每隔几分钟打开一个问题之前使用搜索功能。这已经被描述过很多次了。

Hello, I tried all the previous methods and the results are still the same. Would you please give me some advice?
![image](https://github.com/user-attachments/assets/bae177b6-6f7d-4c50-8da1-68f2ada1156c)

**Comment by robinschmid** [comment]
Please do not open multiple issues for the same thing. This is a community project and the documentation and old issues contain a lot of information.
