### ISSUE TITLE
MzML combined ion mobility representation supported?

### ISSUE THREAD

**Issue by chambm** [mzmine/mzmine#2168]
### Basic information

* My operating system and version: Windows 11
* My mzmine version: 4.3

### What happened

* Please describe what happened and how it differs from what you expected to happen.
I imported an mzML converted from a timsTOF file and the native TDF .d. The mzML uses the combined ion mobility representation. The results of importing the mzML are almost entirely blank, while the results of importing the .d show what I expect (given the same default noise filters). Both files show the same data in SeeMS.

* Please include all parameter values for the mzmine modules you used. 
Defaults.

* Please upload screenshots of any errors **and** your log/mzmine.log file.
![image](https://github.com/user-attachments/assets/5292be47-cc73-46b5-9c0c-5006c858399a)
![image](https://github.com/user-attachments/assets/c5caa6c3-549f-4b1b-8ca0-fc14d93e0bfd)
![image](https://github.com/user-attachments/assets/63fc185f-bcd0-476a-861e-735d08d8c632)

[mzmine_0_0.log](https://github.com/user-attachments/files/17510484/mzmine_0_0.log)

* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
* Issues opened without an example project are unlikely to be processed

I can't seem to save a standalone project without logging in. Is that by design?

Here are more trimmed down versions of the files shown above: 
[Hela_QC_PASEF_Slot1-first-6-frames.d.zip](https://github.com/user-attachments/files/17510775/Hela_QC_PASEF_Slot1-first-6-frames.d.zip)
![image](https://github.com/user-attachments/assets/4b5a97cf-36ff-4451-b05c-c5021e8049e7)

Again, I'm able to see the same data in the .d (left) and mzML (right).

**Comment by chambm** [comment]
Oh I forgot to mention that the automatic axis range calculations are broken with the highly subsetted data files attached above. The base peak vs. retention time pane in particular refused to center around the single 60 sec MS1 data point.

**Comment by SteffenHeu** [comment]
Hi @chambm,

yes the combined IMS representation is not supported by mzmine. 
When i implemented the IMS support from mzml i had a quick look for what's happening with that setting and could not figure it out. Do you have a documentation for it?
I always assumed it would just write all signals of the raw mobility subscans into a single scan in the mzml, but without combining the intensities. But apparently that's not the case.

Generally, we recommend using the Bruker .d files directly, because they have a smaller footprint and are mostly faster to load than the mzml version.

**Comment by chambm** [comment]
I used Bruker so I could compare loading the same file into mzmine from both native .d and mzML. I described the combined representation in the Mobilion issue. It does not combine intensities.

**Comment by SteffenHeu** [comment]
Ok, let's move the discussion to the other issue then.
