### ISSUE TITLE
I used the education email to register to use mzmine4.2, but the 30-day trial period has expired. How can I apply for the one-year academic use period? It's urgent. Thank you.

### ISSUE THREAD

**Issue by Sclllllll** [mzmine/mzmine#2189]
![image](https://github.com/user-attachments/assets/7dbe5d38-7fb4-4dd1-89ee-3aa2fae66067)

**Comment by ansgarkorf** [comment]
Please send an email to info@mzio.io

**Comment by jsalcedo23** [comment]
Good evening, it just happened the same to me last week. In my case the version is 4.5.20 on a Mac M1. I've sent the email to info@mzio.io but haven't got reply yet.

My institution is the Spanish Research Council (CSIC), in case needed. 

Thanks in advance

Jaime
