### ISSUE TITLE
Error of task opening file java.io.IOException:...

### ISSUE THREAD

**Issue by calderod** [mzmine/mzmine#2191]
### Basic information

* My operating system and version: Windows 10 OS
* My mzmine version: 2.53

### What happened

When I try to import Thermo .raw files with "Raw Data Methods" it generates this error. What do I need to do to fix this error?

* Please include all parameter values for the mzmine modules you used.  
* I don't have any specific project parameters and values. it is just a default program
* Please upload screenshots of any errors **and** your log/mzmine.log file.
* ![11-4-2024 MZmine 2 53 error](https://github.com/user-attachments/assets/0b48189d-7d21-41d2-b7ea-ddd187b6598a)
* **Please upload a standalone mzmine project file (or a batch + raw files) that demonstrates the problem you are reporting.** You can use Google Drive, Dropbox, or a similar repository to upload the project.
Here is a link to .raw file for you to try: https://app.box.com/s/gk27kgvyzewnjlzsmn7v4xpotx8yb1na

**Comment by SteffenHeu** [comment]
Hi @calderod 
we do no longer provide support or fixes for mzmine 2 (or 3). You can try mzmine 4 here: https://github.com/mzmine/mzmine/releases. If you desperately need mzmine 2 for this task, i recommend to convert to mzml.
