### ISSUE TITLE
Export data from Volcano Plot

### ISSUE THREAD

**Issue by AntoineEtourneau** [mzmine/mzmine#2197]
After creating a Volcano Plot on mzmine 4.1.0 from a feature list, when exporting the data to Excel, we get a table with the columns log2(fold change) and -log10(p-Value) but not associated with the feature ID, mass or retention time. This association would be useful.

The information exists since we can already click on each point of the volcano blot to obtain the bloxplot with the corresponding feature ID.

So my question is: would it be possible when exporting to add information on the feature ID at a minimum, or even the m/z and RT?

**Comment by SteffenHeu** [comment]
Good idea, will add the feature id as a z-axis, so it's in the exported data, which will also include the tooltip.
