### ISSUE TITLE
MzMine 3.4.16 Eror- Java Exception ıllegal base64 character 0x3e

### ISSUE THREAD

**Issue by sulekaravus** [mzmine/mzmine#2238]
* My operating system and version: macOS Monterey 12.5
* My mzmine version: 3.4.16

I have not performed this analysis before; this will be my first time. I have both the MzML and thermoRaw versions of the same file, but I am encountering different error codes when trying to open each of them. How can I resolve this issue?

<img width="1390" alt="Ekran Resmi 2024-11-19 10 22 25" src="https://github.com/user-attachments/assets/18a64ff9-097e-4908-8ee2-d326b72453c2">
<img width="1396" alt="Ekran Resmi 2024-11-19 10 21 35" src="https://github.com/user-attachments/assets/3ee237c2-5750-43a5-9c84-31e366053b7b">
<img width="679" alt="Ekran Resmi 2024-11-19 10 22 57" src="https://github.com/user-attachments/assets/74716fc1-9d8a-449c-a60e-110559a86759">

**Comment by ansgarkorf** [comment]
Hi, please update to version 4.3, read the raw data import documentation, and test if the problem was fixed.

**Comment by robinschmid** [comment]
This should be fixed in the latest version. 
It is because of special symbols in the raw file
