### ISSUE TITLE
Typographical Error in “Override default mobility bin witdh (scans)” in IMS Expander Module

### ISSUE THREAD

**Issue by BioGavin** [mzmine/mzmine#2256]
Dear MZmine Development Team,

I noticed a typographical error in the IMS Expander module within the MZmine (v4.3.0) GUI. The label “Override default mobility bin witdh (scans)” contains a misspelling: “witdh” should be corrected to “width”.

![image](https://github.com/user-attachments/assets/4fc2d564-044e-4a25-8838-514b381c6f73)

This minor issue appears in the parameter settings window for the IMS Expander module, as shown in the attached screenshot. While it does not affect functionality, correcting it would improve clarity and user experience.

Thank you for your attention to this detail, and for your continued work on this excellent tool!

Best regards,
Gavin

**Comment by SteffenHeu** [comment]
fixed in #2257
