### ISSUE TITLE
Chromatogram resolver, Local minimum resolver: Issue with Peak duration range

### ISSUE THREAD

**Issue by anbemp** [mzmine/mzmine#786]
* My operating system: Windows 11 Pro, 64 bits
* My MZmine version: 3

Hi, I am getting started with MZmine3 to develop nontarget screening strategies to process LC-HRMS data (converted to mzXML files). 
I have found a strict filtering of the number of features when I reduce the Peak duration range in the Local minimum resolver from 0.5 to 0.3 min. The chromatographic peak width of my features are around 0.2-0.25 min, so in terms of workflow optimization, I checked the reduction of the number of features by applying different parameters. For example, I checked the presence of an IS (m/z 245.1518 at 10.12 min). In the preview option of the Local minimum resolver, I observed that this chromatographic peak which has 0.25 min of peak width is not detected when the Peak duration range is set from 0 - 0.3 min, while it is detected when this parameter is set from 0 - 0.5 min. Please, find below the details of my workflow:

**Mass detection**
Retention time: autorange
MS level: 1
Polarity: Any
Spectrum type: Any

**Feature detection - LC-MS - Chromatogram builder**
Min group size in # of scans: 5
Group intensity threshold: 1.0E5
Min highest intensity: 5.0E5
Scan to scan accuracy 0.02 m/z or 10 ppm

**Smoothing**
Algorithm: Savitzky Golay
Retention time smoothing: 5

**Chromatogram resolver, Local minimum resolver**
Dimension: Retention time
Chromatographic threshold: 90%
Minimum search range RT: 0.075
Minimum relative height: 0%
Minimum absolute height: 1.0E6
Min ratio of peak/top edge: 2
_Peak duration range (min): 0 - 0.3_
Min of # data points: 5

Please, find attached a screenshot of the irregular behavior using both parameters.
Peak duration range: 0 - 0.3 min
![image](https://user-images.githubusercontent.com/109214197/178714927-3a41cb2d-6b0d-443c-98c7-4dc2682e2752.png)
Peak duration range: 0 - 0.5 min
![image](https://user-images.githubusercontent.com/109214197/178715050-480b80c4-0e29-49ec-9cec-6d88e1a709ff.png)

Thank you for your time and help.

**Comment by anbemp** [comment]
Just an additional comment: the version of MZmine I am using is 3.1.0-beta

Thanks in advanced!

**Comment by SteffenHeu** [comment]
My guess is that the detected peak is tailing and the taling is still recognised as a part of the peak. Therefore it extends for more than the expected range.

You can try a different resolver, but that's the expected behaviour for the local minimum resolver.
